In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sales_data.csv")
df.head()

         Date     Product  Quantity  Price Customer_ID Region  Total_Sales
0  2024-01-01       Phone         7  37300     CUST001   East       261100
1  2024-01-02  Headphones         4  15406     CUST002  North        61624
2  2024-01-03       Phone         2  21746     CUST003   West        43492
3  2024-01-04  Headphones         1  30895     CUST004   East        30895
4  2024-01-05      Laptop         8  39835     CUST005  North       318680

In [3]:
df.shape

(100, 7)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         100 non-null    object
 1   Product      100 non-null    object
 2   Quantity     100 non-null    int64
 3   Price        100 non-null    int64
 4   Customer_ID  100 non-null    object
 5   Region       100 non-null    object
 6   Total_Sales  100 non-null    int64
dtypes: int64(3), object(4)
memory usage: 5.6+ KB

In [5]:
df.isnull().sum()

Date           0
Product        0
Quantity       0
Price          0
Customer_ID    0
Region         0
Total_Sales    0
dtype: int64

In [6]:
df = df.fillna(0)

In [7]:
df["Total_Sales"] = df["Quantity"] * df["Price"]
df.head()

         Date     Product  Quantity  Price Customer_ID Region  Total_Sales
0  2024-01-01       Phone         7  37300     CUST001   East       261100
1  2024-01-02  Headphones         4  15406     CUST002  North        61624
2  2024-01-03       Phone         2  21746     CUST003   West        43492
3  2024-01-04  Headphones         1  30895     CUST004   East        30895
4  2024-01-05      Laptop         8  39835     CUST005  North       318680

In [10]:
total_revenue = df["Total_Sales"].sum()
highest_sale = df["Total_Sales"].max()
lowest_sale = df["Total_Sales"].min()

print("Total Revenue:", total_revenue)
print("Highest Sale:", highest_sale)
print("Lowest Sale:", lowest_sale)

Total Revenue: 12365048
Highest Sale: 373932
Lowest Sale: 6540

In [11]:
best_product = df.groupby("Product")["Quantity"].sum().idxmax()
print("Best Selling Product:", best_product)

Best Selling Product: Laptop